### ISSUE TITLE
Recommend atreugo increase beforeroute viewfn

### ISSUE THREAD

**Issue by imxxiv** [savsgio/atreugo#45]
I understand, httpserver before the router, should be able to increase the processing steps.
Before the project using nginx + lua, before the request is routed, can do ip whitelist , ip blacklist, waf, etc.
But middleware is operating after routing.

**Comment by imxxiv** [comment]
[It proposed to consider the 200 response middleware.](https://github.com/savsgio/atreugo/issues/37)
Middleware as an execution unit, only direct response when an error status code, I feel there is a lack of logic, middleware should be able to reply directly with all status codes according to the situation, only to return 0 middleware, is the program continue the process.
Currently middleware can only do exclude, but could not complete some prefabricated responses such as cache, etc.

**Comment by savsgio** [comment]
I'm thinking/working about these to add the logic to prevent the view execution.

**Comment by savsgio** [comment]
I've just added a `ctx.SkipView()` to prevent the view execution in before middlewares.

Be careful, because it was mandatory to refactor middlewares. Now, they returns an error and not the status code and error.

If you want to continue to next middleware/filter/view, call `ctx.Next()` or if you want to send a response and stop execution, call to `ctx.TextResponse`,  `ctx.JSONResponse`, etc
