### ISSUE TITLE
Feature Request: Graceful Restart and Auto-Update

### ISSUE THREAD

**Issue by kokizzu** [savsgio/atreugo#56]
Similar to what [overseer](https://github.com/jpillora/overseer) do

**Comment by savsgio** [comment]
Hi @kokizzu ,

I couldn't see the link!

What do you need exactly?

**Comment by savsgio** [comment]
Graceful restart must be implemented on top of atreugo, because Go must be recompiled if code change.
So you could you the [Reuseport](https://github.com/savsgio/atreugo/blob/master/types.go#L75) to run two server instances (old and new) in the same port without hold to server requests and kill the old version, but this implementation must be out of framework, because i couldn't know the best way for each case.

**Comment by savsgio** [comment]
Please see: https://github.com/savsgio/atreugo/issues/39#issuecomment-529931371

**Comment by kokizzu** [comment]
i fixed the link, auto update replaces binary and restart the server when there's a new update

**Comment by savsgio** [comment]
You could implement these features without matters  with overseers or similars libs.

I prefer to not include it, by reasons that i gave you and because they are include some complexity to the framework that is not  responsability of Atreugo.

Thanks equally. 😃

**Comment by savsgio** [comment]
Maybe, in the future, I can consider doing it.
