### ISSUE TITLE
Only 394 starts ?

### ISSUE THREAD

**Issue by benjamin-yin001** [savsgio/atreugo#77]
I test atreugo several months ago, very fast
Now I go back for some go web frameworks, I found it is only 394 starts.
I found another framework Fiber. It is more late than atreugo, but got 3.1K stars.

**Comment by savsgio** [comment]
Hi @benjamin-yin001,

I try to do a very fast micro-framework to unify the use of the router, middlewares and extra functionalities with fasthttp without lose performance.

Fiber has an equal/similar API to the ExpresJS and a great documentation and i think that the people really like that, because to much people know ExpresJS framework, among other things

So I just try to keep the fasthttp API but more extended and functional with a great performance.
But I have pending to improve the documentation, i know it.

**Comment by savsgio** [comment]
Thanks for use Atreugo 👍 i feel happy haha.
