### ISSUE TITLE
Instrumenting servers / paths to add metrics doesn't work when view returns an error

### ISSUE THREAD

**Issue by eranharel** [savsgio/atreugo#86]
I was trying to add instrumentation around the `Atreugo` server and/or around `Path`s.
I created a middleware and used `UseBefore` and `UseAfter()` to wire it, and the middle ware registers the processing time, response status, errors, etc.

The problem is, that when a view returns an error, the `After` middleware doesn't get called, and instead (I think) only the ErrorView is called.

This for me sounds like a really problematic flow as it prevents you from writing such middlewares unless I'm missing something here.

BTW, I saw a few closed tickets here about implementing something similar, but the code snippets in the tickets won't work, as the After middleware won't get called.

Is there a way to fix this?
Am I doing it wrong?

**Comment by savsgio** [comment]
Hi @eranharel,

Sorry for delayed answer.

The workflow is interrupted when you return an error in a middleware (before/after) or view and the `ErrorView` will be executed, so if you want to continue the chain execution you should save the error (with `ctx.SetUserValue("viewErr", err)`) an not return it, proccessing that error in your after middleware.

Keep in mind, if you return an error in a view or before middleware, and later return another error after, the execution could be unstable due to don't know when stop the execution of the request, and the atreugo interface would be more complex.


Thanks for use Atreugo 😉
