### ISSUE TITLE
Possible race condition in context propagation

### ISSUE THREAD

**Issue by dmarkhas** [savsgio/atreugo#90]
Apparently, trying to do the below may result in a race condition:

```
func(ctx *atreugo.RequestCtx) error {

		newCtx, cancel := context.WithTimeout(ctx, time.Second*1)
		defer cancel()

		return ctx.TextResponse("OK")
}
```

Internally, since `*atreugo.RequestCtx` is a custom context implementation, both `context.WithTimeout` and `context.WithDeadline` create a go routine for watching the parent's `Done` channel:

https://go.googlesource.com/go/+/refs/heads/release-branch.go1.15/src/context/context.go#278

This causes a race condition between atreugo's `ReleaseRequestCtx` and Go's internal context-watching go routine.

Is there some way to clone the context when propagating it, to avoid this race condition?

**Comment by gurich92** [comment]
@dmarkhas 
Also faced that race condition.

For workaround I used the underlying fasthttp.RequestCtx, since if my understanding is correct - it's main context here, because atreugo.RequestCtx is just a top-level "abstraction"(https://github.com/savsgio/atreugo/blob/96c313bfec073a4a47cf3c5d1feef54cf9af11e5/types.go#L387), but for all the routing, timeouts etc standard fasthttp.Router and so fasthttp.RequestCtx is used.

So your code should work well if it will be like this:
```
func(ctx *atreugo.RequestCtx) error {

		newCtx, cancel := context.WithTimeout(ctx.RequestCtx, time.Second*1)
		defer cancel()

		return ctx.TextResponse("OK")
}
```

**Comment by savsgio** [comment]
Hi @dmarkhas,

Sorry for delayed answer.

I will try to research about this race condition, but in the meanwhile, use the underlying fasthttp.RequestCtx, just like @gurich92 says.

**Comment by savsgio** [comment]
Hi @dmarkhas and @gurich92,

Sorry for delayed answer, but been busy.

I researched about this race condition and could see that `fasthttp.RequestCtx` (and also `atreugo.RequestCtx`)  are unsafed to use concurrently (https://github.com/valyala/fasthttp/blob/master/server.go#L554).

So, due to the `context.WithTimeout()` could create a gorutine to check the state. It's better to use `context.Backround()` instead of the `RequestCtx`.

Thanks!
